// <auto-generated />
using System;
using EFC;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFC.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20180624072615_First")]
    partial class First
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.School.Exam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DbCreatedAt");

                    b.Property<string>("DbCreatedBy");

                    b.Property<DateTime>("DbModifiedAt");

                    b.Property<string>("DbModifiedBy");

                    b.Property<int?>("SubjectId");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("Domain.School.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DbCreatedAt");

                    b.Property<string>("DbCreatedBy");

                    b.Property<DateTime>("DbModifiedAt");

                    b.Property<string>("DbModifiedBy");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Domain.School.StudentExam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DbCreatedAt");

                    b.Property<string>("DbCreatedBy");

                    b.Property<DateTime>("DbModifiedAt");

                    b.Property<string>("DbModifiedBy");

                    b.Property<int?>("ExamId");

                    b.Property<int?>("StudentId");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentExams");
                });

            modelBuilder.Entity("Domain.School.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DbCreatedAt");

                    b.Property<string>("DbCreatedBy");

                    b.Property<DateTime>("DbModifiedAt");

                    b.Property<string>("DbModifiedBy");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("Domain.School.Exam", b =>
                {
                    b.HasOne("Domain.School.Subject", "Subject")
                        .WithMany("Exams")
                        .HasForeignKey("SubjectId");

                    b.OwnsOne("Domain.School.ExamDifficulty", "Difficulty", b1 =>
                        {
                            b1.Property<int?>("ExamId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Value")
                                .HasColumnName("Difficulty");

                            b1.ToTable("Exams");

                            b1.HasOne("Domain.School.Exam")
                                .WithOne("Difficulty")
                                .HasForeignKey("Domain.School.ExamDifficulty", "ExamId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("Domain.School.StudentExam", b =>
                {
                    b.HasOne("Domain.School.Exam", "Exam")
                        .WithMany()
                        .HasForeignKey("ExamId");

                    b.HasOne("Domain.School.Student", "Student")
                        .WithMany("Exams")
                        .HasForeignKey("StudentId");

                    b.OwnsOne("Domain.School.Grade", "Grade", b1 =>
                        {
                            b1.Property<int?>("StudentExamId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Value")
                                .HasColumnName("Grade");

                            b1.ToTable("StudentExams");

                            b1.HasOne("Domain.School.StudentExam")
                                .WithOne("Grade")
                                .HasForeignKey("Domain.School.Grade", "StudentExamId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
