// <auto-generated />
using System;
using EFC;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Domain.School;

namespace EFC.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20180624174741_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.School.Exam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DbCreatedAt");

                    b.Property<string>("DbCreatedBy");

                    b.Property<DateTime>("DbModifiedAt");

                    b.Property<string>("DbModifiedBy");

                    b.Property<string>("Difficulty")
                        .HasConversion(new ValueConverter<ExamDifficulty, string>(v => default(string), v => default(ExamDifficulty), new ConverterMappingHints()));

                    b.Property<int?>("SubjectId");

                    b.Property<long>("Time");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("Domain.School.SchoolClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Number");

                    b.HasKey("Id");

                    b.ToTable("SchoolClasses");
                });

            modelBuilder.Entity("Domain.School.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DbCreatedAt");

                    b.Property<string>("DbCreatedBy");

                    b.Property<DateTime>("DbModifiedAt");

                    b.Property<string>("DbModifiedBy");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<int?>("SchoolClassId");

                    b.HasKey("Id");

                    b.HasIndex("SchoolClassId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Domain.School.StudentExamGrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DbCreatedAt");

                    b.Property<string>("DbCreatedBy");

                    b.Property<DateTime>("DbModifiedAt");

                    b.Property<string>("DbModifiedBy");

                    b.Property<int?>("ExamId");

                    b.Property<int?>("StudentId");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentExams");
                });

            modelBuilder.Entity("Domain.School.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DbCreatedAt");

                    b.Property<string>("DbCreatedBy");

                    b.Property<DateTime>("DbModifiedAt");

                    b.Property<string>("DbModifiedBy");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("Domain.School.Exam", b =>
                {
                    b.HasOne("Domain.School.Subject", "Subject")
                        .WithMany("Exams")
                        .HasForeignKey("SubjectId");
                });

            modelBuilder.Entity("Domain.School.Student", b =>
                {
                    b.HasOne("Domain.School.SchoolClass")
                        .WithMany("Students")
                        .HasForeignKey("SchoolClassId");
                });

            modelBuilder.Entity("Domain.School.StudentExamGrade", b =>
                {
                    b.HasOne("Domain.School.Exam", "Exam")
                        .WithMany()
                        .HasForeignKey("ExamId");

                    b.HasOne("Domain.School.Student", "Student")
                        .WithMany("ExamGrades")
                        .HasForeignKey("StudentId");

                    b.OwnsOne("Domain.School.Grade", "Grade", b1 =>
                        {
                            b1.Property<int?>("StudentExamGradeId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Value")
                                .HasColumnName("Grade");

                            b1.ToTable("StudentExams");

                            b1.HasOne("Domain.School.StudentExamGrade")
                                .WithOne("Grade")
                                .HasForeignKey("Domain.School.Grade", "StudentExamGradeId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
